FROM php:7.2.2-cli

RUN apt-get update \
    && apt-get -y install git unzip

RUN pecl install xdebug-2.6.0 \
    && docker-php-ext-enable xdebug

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
RUN composer config --global repo.packagist composer https://packagist.org

WORKDIR /project
