services:
  symfony_apm_agent.open_transaction_listener:
    class: '%symfony_apm_agent.open_transaction_listener%'
    arguments:
      - '@Psr\Log\LoggerInterface'
      - '@symfony_apm_agent.open_transaction_factory'
    tags:
      - { name: kernel.event_listener, event: kernel.request, priority: '%symfony_apm_agent.listener_priorities.request%' }

  symfony_apm_agent.close_transaction_listener:
    class: '%symfony_apm_agent.close_transaction_listener%'
    arguments:
      - '@Psr\Log\LoggerInterface'
      - '@TechDeCo\ElasticApmAgent\Client'
      - '@symfony_apm_agent.transaction_request_factory'
    tags:
      - { name: kernel.event_listener, event: kernel.terminate, priority: '%symfony_apm_agent.listener_priorities.terminate%' }

  symfony_apm_agent.open_transaction_factory:
    class: MikolFaro\SymfonyApmAgentBundle\Factory\OpenTransactionFactory
    arguments:
      - '@Symfony\Component\HttpKernel\KernelInterface'
      - '@Psr\Log\LoggerInterface'

  symfony_apm_agent.transaction_request_factory:
    class: MikolFaro\SymfonyApmAgentBundle\Factory\TransactionRequestFactory
    arguments:
      - '@Psr\Log\LoggerInterface'
      - '@Symfony\Component\Security\Core\Security'
      - '@MikolFaro\SymfonyApmAgentBundle\Factory\SystemFactoryInterface'

  TechDeCo\ElasticApmAgent\Client:
    class: 'TechDeCo\ElasticApmAgent\Client\HttplugAsyncClient'
    arguments:
      - '@Psr\Log\LoggerInterface'
      - '@TechDeCo\ElasticApmAgent\ClientConfiguration'
      - # '@Http\Client\HttpAsyncClient'
      - # '@Http\Message\MessageFactory'

  TechDeCo\ElasticApmAgent\ClientConfiguration:
    class: TechDeCo\ElasticApmAgent\ClientConfiguration
    arguments:
      - '%symfony_apm_agent.server_url%'

  MikolFaro\SymfonyApmAgentBundle\Factory\SystemFactoryInterface:
    class: MikolFaro\SymfonyApmAgentBundle\Factory\SystemFactory
    arguments:
      - '@Symfony\Component\HttpKernel\KernelInterface'
      - '@Psr\Log\LoggerInterface'
